/**
 * GENERATED by scripts/build-catalog.mjs — do not edit by hand.
 * Source of truth: content/artworks.json, content/exhibition.md, content/artist-bio.md
 */

export type Availability = "available" | "reserved" | "sold" | "not-for-sale";

export interface Artwork {
  id: string;
  title: string;
  year: number;
  medium: string;
  dimensions: string;
  price: number | null;
  currency: string;
  availability: Availability;
  image: string;
  shortDescription: string;
  themes: string[];
  signature?: boolean;
  exhibitionId: string;
}

export const ARTWORKS: Artwork[] = [
  {
    "availability": "available",
    "currency": "USD",
    "dimensions": "30 × 40 in",
    "exhibitionId": "thresholds-2026",
    "id": "blue-passage",
    "image": "/artworks/blue-passage.webp",
    "medium": "Oil and cold wax on panel",
    "price": 2400,
    "shortDescription": "A study of memory, distance, and interrupted movement.",
    "signature": true,
    "themes": [
      "memory",
      "thresholds",
      "movement"
    ],
    "title": "Blue Passage",
    "year": 2026
  },
  {
    "availability": "available",
    "currency": "USD",
    "dimensions": "24 × 36 in",
    "exhibitionId": "thresholds-2026",
    "id": "after-the-rain",
    "image": "/artworks/after-the-rain.webp",
    "medium": "Oil and cold wax on panel",
    "price": 1800,
    "shortDescription": "Wet pavement light, held a moment longer than it lasts.",
    "themes": [
      "memory",
      "weather",
      "light"
    ],
    "title": "After the Rain",
    "year": 2025
  },
  {
    "availability": "reserved",
    "currency": "USD",
    "dimensions": "36 × 36 in",
    "exhibitionId": "thresholds-2026",
    "id": "threshold-no-3",
    "image": "/artworks/threshold-no-3.webp",
    "medium": "Oil, cold wax, and graphite on panel",
    "price": 2600,
    "shortDescription": "The third attempt at painting a doorway that won't stay still.",
    "themes": [
      "thresholds",
      "repetition",
      "movement"
    ],
    "title": "Threshold No. 3",
    "year": 2026
  },
  {
    "availability": "sold",
    "currency": "USD",
    "dimensions": "20 × 24 in",
    "exhibitionId": "thresholds-2026",
    "id": "salt-meridian",
    "image": "/artworks/salt-meridian.webp",
    "medium": "Oil and cold wax on panel",
    "price": 1400,
    "shortDescription": "A coastline remembered wrong, on purpose.",
    "themes": [
      "memory",
      "place",
      "erosion"
    ],
    "title": "Salt Meridian",
    "year": 2024
  },
  {
    "availability": "not-for-sale",
    "currency": "USD",
    "dimensions": "18 × 24 in",
    "exhibitionId": "thresholds-2026",
    "id": "wintering-light",
    "image": "/artworks/wintering-light.webp",
    "medium": "Oil on linen",
    "price": null,
    "shortDescription": "Kept by the artist. Shown here so the series reads complete.",
    "themes": [
      "light",
      "seasons",
      "keeping"
    ],
    "title": "Wintering Light",
    "year": 2025
  },
  {
    "availability": "available",
    "currency": "USD",
    "dimensions": "48 × 24 in",
    "exhibitionId": "thresholds-2026",
    "id": "the-long-hallway",
    "image": "/artworks/the-long-hallway.webp",
    "medium": "Oil and cold wax on panel",
    "price": 2900,
    "shortDescription": "Perspective as a feeling: the corridor before the news.",
    "themes": [
      "thresholds",
      "anticipation",
      "interiors"
    ],
    "title": "The Long Hallway",
    "year": 2026
  }
];

export const EXHIBITION_STATEMENT: string = "# SAMPLE EXHIBITION STATEMENT — replace with Zak's real statement\n\n> **Everything in `content/` is sample data** for scaffolding the build.\n> Replace these files with Zak's approved materials before any public launch.\n\n# Thresholds\n\n## A solo exhibition by Zak\n\nSix works about the moments between things: the hallway before the\ndoor opens, the season before it turns, the breath before speaking.\nZak paints thresholds — not the places we arrive, but the passages\nwe move through.\n\nThese paintings were made over eighteen months in Zak's studio,\nworking in oil and cold wax on panel. Layers are built up and\nscraped back; what remains is what survived the crossing.\n\n*Thresholds* runs October 9 – November 21, 2026.\n";

export const ARTIST_BIO: string = "# SAMPLE ARTIST BIO — replace with Zak's real bio\n\n> **Sample data.** Replace with Zak's approved biography before launch.\n\nZak is a painter working in oil and cold wax on panel. Their work\nexplores memory, distance, and the physical feeling of moving through\ntransitional spaces — hallways, shorelines, seasons.\n\nZak studied painting at [school], has exhibited in [cities], and keeps\na studio practice grounded in material experimentation: building up\nsurfaces, scraping them back, and letting what survives become the\npainting.\n\nFor inquiries about available work, use the interest form on any\nartwork page, or write to hello@example.com. (Sample contact —\nreplace with Zak's real contact.)\n";

export function getArtwork(id: string): Artwork | null {
  return ARTWORKS.find((a) => a.id === id) ?? null;
}

export function formatPrice(a: Artwork): string {
  if (a.price == null) return "Price on request";
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: a.currency,
    maximumFractionDigits: 0,
  }).format(a.price);
}

export function availabilityLabel(a: Artwork): string {
  switch (a.availability) {
    case "available": return "Available";
    case "reserved": return "Reserved — ask Zak for details";
    case "sold": return "Sold";
    case "not-for-sale": return "Not for sale";
  }
}
