#!/usr/bin/env node
/**
 * Build step: inline content/ into functions/_core/catalog.ts so the
 * SpaceFast serverless functions carry the artwork catalog with them.
 * Single source of truth stays in content/ — never edit catalog.ts by hand.
 *
 *   node scripts/build-catalog.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const contentDir = join(root, "content");
const outFile = join(root, "functions", "_core", "catalog.ts");

const artworks = JSON.parse(readFileSync(join(contentDir, "artworks.json"), "utf-8")).artworks;
const exhibition = readFileSync(join(contentDir, "exhibition.md"), "utf-8");
const bio = readFileSync(join(contentDir, "artist-bio.md"), "utf-8");

const ts = `/**
 * GENERATED by scripts/build-catalog.mjs — do not edit by hand.
 * Source of truth: content/artworks.json, content/exhibition.md, content/artist-bio.md
 */

export type Availability = "available" | "reserved" | "sold" | "not-for-sale";

export interface Artwork {
  id: string;
  title: string;
  year: number;
  medium: string;
  dimensions: string;
  price: number | null;
  currency: string;
  availability: Availability;
  image: string;
  shortDescription: string;
  themes: string[];
  signature?: boolean;
  exhibitionId: string;
}

export const ARTWORKS: Artwork[] = ${JSON.stringify(artworks, null, 2)};

export const EXHIBITION_STATEMENT: string = ${JSON.stringify(exhibition)};

export const ARTIST_BIO: string = ${JSON.stringify(bio)};

export function getArtwork(id: string): Artwork | null {
  return ARTWORKS.find((a) => a.id === id) ?? null;
}

export function formatPrice(a: Artwork): string {
  if (a.price == null) return "Price on request";
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: a.currency,
    maximumFractionDigits: 0,
  }).format(a.price);
}

export function availabilityLabel(a: Artwork): string {
  switch (a.availability) {
    case "available": return "Available";
    case "reserved": return "Reserved — ask Zak for details";
    case "sold": return "Sold";
    case "not-for-sale": return "Not for sale";
  }
}
`;

mkdirSync(join(root, "functions", "_core"), { recursive: true });
writeFileSync(outFile, ts);
console.log(`wrote ${outFile} (${artworks.length} artworks)`);
